[features]
resolution = true
skip-lint = false

[programs.devnet]
veil_rfq = "5vAQqq7ZFfoL4orYsUKnUbSaJqmYeh88PQCuj451531F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/veil-rfq"]

[scripts]
test = "tsx tests/rfq.test.ts"

[toolchain]
solana_version = "1.18.26"