[toolchain]
anchor_version = "1.0.0"
solana_version = "3.1.10"

[features]
resolution = true
skip-lint = false

[programs.devnet]
veil_rfq_match = "6gRGKyvy4qJjSCBcxh6uaaSeih1ZxVCDt926Y3Fp8BVC"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/veil-rfq-match"]

[hooks]
